### ISSUE TITLE
Add Time Column to Overview

### ISSUE THREAD

**Issue by csch-joa** [CompassSecurity/PurpleOps#17]
Adding the time column to the overview of all testcases could help identify the relevant cases for the blue team more easily.

Credits to Johnnie for the idea :P

**Comment by fxai** [comment]
which time are you looking for? you can add Start and Modify time
![image](https://github.com/user-attachments/assets/d2489da6-83ba-4295-8726-1b450e73cca1)

**Comment by fxai** [comment]
added start time selected as default for blue team 
fbaf247ba7fbf8200f2cf4d3abf83cf12f46481e
