### ISSUE TITLE
Password Invisible When Re-Generated

### ISSUE THREAD

**Issue by csch-joa** [CompassSecurity/PurpleOps#7]
When creating a new user and clicking on "Random", the password is displayed:
![image](https://github.com/user-attachments/assets/a7bbe7e7-2d9c-4721-8200-63e0a4e75e91)

However, when doing the same for an existing user, the newly generated password remains masked:
![image](https://github.com/user-attachments/assets/bbf72be1-c5f2-4a4f-a776-978728149efe)

Temporary workaround to retrieve the password: look at the request payload in the browser's network tab.

**Comment by fxai** [comment]
fixed in f6a29ce5b0981a152e805b25e397a0135d73a8a6
